import 'dart:convert';
import 'dart:typed_data';

import 'package:fl_clash/security/security.dart';
import 'package:flutter_test/flutter_test.dart';

const _testPublicKey = '''
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsRmfvB0FzaHpWjcMTCZo
ncSowVjGOBnV7PxntpLJnvBciMxtZB7j9UWAUMG5Azg5i5H7Jl9o3tOBKytkQ2ZL
OHbDrSAEKSLQKZONP5txnoYYDufhKJ0uVsS6IIgiq3HTdFsQxz6HvlWwntgYZDD+
9jBnsF+E7XbqeSN8jpM5f6t1h50mVSwgjN05H9hEZW14/OcA9VfPbwgGEt4Y8jsr
R/Q+/y1BvUK+Hy47noLwa8PwJHpvcYlPVriVZ4n4wLQ3bC4srh85b5WQMQ48S1s3
xfPxpMnLBJJmH05H96Ducx2kv2seVWdmUvCFtmEZOuXMHAaSNHH4NyzC6f1dFCTp
VwIDAQAB
-----END PUBLIC KEY-----
''';

void main() {
  group('SecureCryptoService', () {
    test('encrypts secure-v2 payload with AES-GCM and RSA-OAEP-SHA256', () {
      final crypto = SecureCryptoService();
      final encrypted = crypto.encryptRequest(
        payload: {
          'method': 'POST',
          'path': '/api/v1/passport/auth/login',
          'headers': <String, String>{},
          'query': <String, String>{},
          'body': {'email': 'user@example.com', 'password': 'secret'},
        },
        publicKeyPem: _testPublicKey,
      );

      expect(encrypted.key.length, 32);
      expect(base64Decode(encrypted.iv).length, 12);
      expect(base64Decode(encrypted.encryptedKey).length, greaterThan(128));
      expect(base64Decode(encrypted.ciphertext).length, greaterThan(16));
    });

    test('uses fresh AES key and IV for each request', () {
      final crypto = SecureCryptoService();

      final first = crypto.encryptRequest(
        payload: _payload(),
        publicKeyPem: _testPublicKey,
      );
      final second = crypto.encryptRequest(
        payload: _payload(),
        publicKeyPem: _testPublicKey,
      );

      expect(first.iv, isNot(second.iv));
      expect(first.encryptedKey, isNot(second.encryptedKey));
      expect(first.ciphertext, isNot(second.ciphertext));
    });

    test('decrypts AES-GCM ciphertext generated by the request encryptor', () {
      final crypto = SecureCryptoService();
      final payload = _payload();
      final encrypted = crypto.encryptRequest(
        payload: payload,
        publicKeyPem: _testPublicKey,
      );

      final decrypted = crypto.decryptResponse(
        iv: encrypted.iv,
        ciphertext: encrypted.ciphertext,
        key: encrypted.key,
      );

      expect(decrypted['method'], payload['method']);
      expect(decrypted['path'], payload['path']);
    });

    test('rejects tampered AES-GCM ciphertext', () {
      final crypto = SecureCryptoService();
      final encrypted = crypto.encryptRequest(
        payload: _payload(),
        publicKeyPem: _testPublicKey,
      );

      expect(
        () => crypto.decryptResponse(
          iv: encrypted.iv,
          ciphertext: base64Encode(List<int>.filled(32, 9)),
          key: encrypted.key,
        ),
        throwsA(isA<SecureHttpException>()),
      );
    });

    test('fails on invalid public key', () {
      final crypto = SecureCryptoService();

      expect(
        () => crypto.encryptRequest(
          payload: _payload(),
          publicKeyPem: 'not-a-public-key',
        ),
        throwsA(isA<SecureHttpException>()),
      );
    });

    test('decrypts mock secure-v2 response payload', () {
      final crypto = _FakeCryptoService();
      final encrypted = crypto.encryptRequest(
        payload: _payload(),
        publicKeyPem: _testPublicKey,
      );
      final decrypted = crypto.decryptResponse(
        iv: 'mock-response-iv',
        ciphertext: 'mock-response-ciphertext',
        key: encrypted.key,
      );

      expect(decrypted['status'], 200);
      expect(decrypted['body'], {'ok': true});
    });
  });

  group('SecureRequest', () {
    test('rejects unsafe paths', () {
      for (final path in [
        'https://backend.example.com/api/v1/user/info',
        '/api/v1/user/../admin',
        r'/api/v1/user\info',
        '/api/v1/user/info?x=1',
        '/admin/user/fetch',
      ]) {
        expect(
          () => SecureRequest(method: 'GET', path: path),
          throwsA(isA<SecureHttpException>()),
          reason: path,
        );
      }
    });

    test('filters dangerous headers while keeping authorization', () {
      final request = SecureRequest(
        method: 'GET',
        path: '/api/v1/user/info',
        headers: {
          'Authorization': 'Bearer token',
          'Host': 'bad.example.com',
          'X-Forwarded-Host': 'bad.example.com',
          'X-App-Version': '1.0.0',
        },
      );

      expect(request.headers['authorization'], 'Bearer token');
      expect(request.headers['x-app-version'], '1.0.0');
      expect(request.headers.containsKey('host'), false);
      expect(request.headers.containsKey('x-forwarded-host'), false);
    });
  });

  group('SecureHttpClient', () {
    test('constructs secure-v2 request and decrypts mock response', () async {
      final crypto = _FakeCryptoService();
      final transport = _FakeTransport((request) {
        return _encryptedResponse(request, crypto);
      });
      final client = _client(transport: transport, cryptoService: crypto);

      final response = await client.post(
        '/api/v1/passport/auth/login',
        body: {'email': 'user@example.com', 'password': 'secret'},
      );

      expect(response.status, 200);
      expect(response.body, {'ok': true});
      expect(
        transport.requests.single.uri.toString(),
        'https://security.example.com/secure-v2/proxy',
      );
      expect(transport.requests.single.headers['x-secure-version'], '2');
      expect(transport.requests.single.headers['x-key-id'], 'main-2026-01');

      final body = jsonDecode(transport.requests.single.body) as Map;
      expect(body['keyId'], 'main-2026-01');
      expect(body['encryptedKey'], isNotEmpty);
      expect(body['iv'], isNotEmpty);
      expect(body['ciphertext'], isNotEmpty);
      expect(crypto.lastPayload?['path'], '/api/v1/passport/auth/login');
    });

    test('rejects missing keyId, publicKey and securityBaseUrl', () async {
      for (final config in [
        _config(keyId: ''),
        _config(publicKey: ''),
        _config(securityBaseUrl: ''),
      ]) {
        final client = SecureHttpClient(
          config: config,
          transport: _FakeTransport((_) => throw StateError('not called')),
          cryptoService: _FakeCryptoService(),
        );

        await expectLater(
          client.get('/api/v1/user/info'),
          throwsA(isA<SecureHttpException>()),
        );
      }
    });

    test('rejects requestId mismatch', () async {
      final crypto = _FakeCryptoService();
      final transport = _FakeTransport((request) {
        return SecureTransportResponse(
          statusCode: 200,
          body: jsonEncode({
            'iv': 'mock-response-iv',
            'ciphertext': 'mock-response-ciphertext',
            'requestId': 'different-id',
          }),
          headers: const {},
        );
      });
      final client = _client(transport: transport, cryptoService: crypto);

      await expectLater(
        client.get('/api/v1/user/info'),
        throwsA(
          isA<SecureHttpException>().having(
            (error) => error.code,
            'code',
            SecureHttpErrorCode.requestIdMismatch,
          ),
        ),
      );
    });

    test('tries backup security base URL after network failure', () async {
      final crypto = _FakeCryptoService();
      var calls = 0;
      final transport = _FakeTransport((request) {
        calls += 1;
        if (calls == 1) {
          throw const SecureHttpException(
            code: SecureHttpErrorCode.network,
            message: 'network failed',
          );
        }
        return _encryptedResponse(request, crypto);
      });
      final client = _client(transport: transport, cryptoService: crypto);

      final response = await client.get('/api/v1/user/info');

      expect(response.status, 200);
      expect(
        transport.requests[0].uri.toString(),
        'https://security.example.com/secure-v2/proxy',
      );
      expect(
        transport.requests[1].uri.toString(),
        'https://security-backup.example.com/secure-v2/proxy',
      );
    });

    test('does not fall back to secure-v1 on secure-v2 rejection', () async {
      final transport = _FakeTransport((request) {
        return SecureTransportResponse(
          statusCode: 403,
          body: jsonEncode({
            'code': 'SECURE_V2_INVALID_KEY_ID',
            'message': 'Invalid secure request',
            'requestId': request.headers['x-request-id'],
          }),
          headers: const {},
        );
      });
      final client = _client(transport: transport);

      await expectLater(
        client.get('/api/v1/user/info'),
        throwsA(
          isA<SecureHttpException>().having(
            (error) => error.code,
            'code',
            SecureHttpErrorCode.secureV2Error,
          ),
        ),
      );
      expect(transport.requests, hasLength(1));
      expect(transport.requests.single.uri.path, '/secure-v2/proxy');
    });
  });

  group('SensitiveLogMasker', () {
    test('masks authorization, password, token, auth data and subscribe URL',
        () {
      const masker = SensitiveLogMasker();
      final masked = masker.mask({
        'authorization': 'Bearer abcdefg123456',
        'password': 'very-secret',
        'token': 'token-value',
        'auth_data': 'auth-data-value',
        'subscribe_url': 'https://example.com/sub?token=abc',
        'email': 'test@example.com',
      }) as Map;

      expect(masked['authorization'], isNot('Bearer abcdefg123456'));
      expect(masked['authorization'], contains('********'));
      expect(masked['password'], isNot('very-secret'));
      expect(masked['token'], isNot('token-value'));
      expect(masked['auth_data'], isNot('auth-data-value'));
      expect(masked['subscribe_url'], isNot(contains('token=abc')));
      expect(masked['email'], 't***@example.com');
    });
  });
}

Map<String, dynamic> _payload() {
  return {
    'method': 'GET',
    'path': '/api/v1/user/info',
    'headers': <String, String>{},
    'query': <String, String>{},
    'body': <String, dynamic>{},
  };
}

SecureConfig _config({
  String securityBaseUrl = 'https://security.example.com',
  String publicKey = _testPublicKey,
  String keyId = 'main-2026-01',
}) {
  return SecureConfig(
    securityBaseUrl: securityBaseUrl,
    backupSecurityBaseUrls: const ['https://security-backup.example.com'],
    keyId: keyId,
    publicKey: publicKey,
    appVersion: '1.0.0',
    platform: 'macos',
  );
}

SecureHttpClient _client({
  SecureTransport? transport,
  SecureCryptoService? cryptoService,
}) {
  return SecureHttpClient(
    config: _config(),
    transport: transport,
    cryptoService: cryptoService ?? _FakeCryptoService(),
    requestIdFactory: () => 'request-1',
    now: () => DateTime.utc(2026, 6, 13),
  );
}

SecureTransportResponse _encryptedResponse(
  _RecordedRequest request,
  _FakeCryptoService crypto,
) {
  return SecureTransportResponse(
    statusCode: 200,
    body: jsonEncode({
      'iv': 'mock-response-iv',
      'ciphertext': 'mock-response-ciphertext',
      'requestId': request.headers['x-request-id'],
    }),
    headers: const {},
  );
}

class _FakeCryptoService extends SecureCryptoService {
  Map<String, dynamic>? lastPayload;

  @override
  EncryptedPayload encryptRequest({
    required Map<String, dynamic> payload,
    required String publicKeyPem,
  }) {
    lastPayload = payload;
    return EncryptedPayload(
      key: Uint8List.fromList(List<int>.filled(32, 7)),
      encryptedKey: base64Encode(List<int>.filled(256, 1)),
      iv: base64Encode(List<int>.filled(12, 2)),
      ciphertext: base64Encode(utf8.encode(jsonEncode(payload))),
    );
  }

  @override
  Map<String, dynamic> decryptResponse({
    required String iv,
    required String ciphertext,
    required Uint8List key,
  }) {
    if (iv != 'mock-response-iv' || ciphertext != 'mock-response-ciphertext') {
      throw const SecureHttpException(
        code: SecureHttpErrorCode.decryptionFailed,
        message: 'mock decrypt failed',
      );
    }
    return {
      'status': 200,
      'headers': <String, String>{},
      'body': {'ok': true},
    };
  }
}

class _FakeTransport implements SecureTransport {
  final SecureTransportResponse Function(_RecordedRequest request) handler;
  final List<_RecordedRequest> requests = [];

  _FakeTransport(this.handler);

  @override
  Future<SecureTransportResponse> post(
    Uri uri, {
    required Map<String, String> headers,
    required String body,
    required Duration timeout,
  }) async {
    final request = _RecordedRequest(uri, headers, body);
    requests.add(request);
    return handler(request);
  }
}

class _RecordedRequest {
  final Uri uri;
  final Map<String, String> headers;
  final String body;

  const _RecordedRequest(this.uri, this.headers, this.body);
}
